execute:
  execute_notebooks: binder
  timeout: 1200
  allow_errors: True

sphinx:
  config:
    html_theme: book-theme
    html_theme_options:
      launch_buttons:
        binderhub_url: "https://mybinder.org"